// Editable starting dimensions in inches, not manufacturer specifications.
export const CATALOG_CATEGORIES = [
  'Living',
  'Bedroom',
  'Storage',
  'Dining & work',
  'Kitchen & laundry',
  'Bathroom',
  'Decor & utility',
  'Make it yours',
] as const
export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number]
type CatalogPreset = {
  kind: string
  category: CatalogCategory
  name: string
  description: string
  width: number
  depth: number
  height: number
  elevation: number
  color: string
}

export const CATALOG = [
  {
    kind: 'bed',
    category: 'Bedroom',
    name: 'Bed',
    description: 'Frame, mattress & pillows',
    width: 60,
    depth: 84,
    height: 36,
    elevation: 0,
    color: '#889f8c',
  },
  {
    kind: 'almirah',
    category: 'Storage',
    name: 'Steel almirah',
    description: 'Steel double doors & lock',
    width: 36,
    depth: 20,
    height: 72,
    elevation: 0,
    color: '#849a99',
  },
  {
    kind: 'dressing',
    category: 'Bedroom',
    name: 'Dressing table',
    description: 'Mirror, drawers & cabinet',
    width: 36,
    depth: 18,
    height: 66,
    elevation: 0,
    color: '#b28c69',
  },
  {
    kind: 'wardrobe',
    category: 'Storage',
    name: 'Wardrobe',
    description: 'Three wooden doors',
    width: 48,
    depth: 22,
    height: 72,
    elevation: 0,
    color: '#a48262',
  },
  {
    kind: 'rack',
    category: 'Storage',
    name: 'RFL rack',
    description: 'Three open plastic shelves',
    width: 20,
    depth: 12,
    height: 27,
    elevation: 0,
    color: '#578799',
  },
  {
    kind: 'sofa-one',
    category: 'Living',
    name: 'One-seat sofa',
    description: 'Upholstered armchair',
    width: 34,
    depth: 34,
    height: 34,
    elevation: 0,
    color: '#a3a18b',
  },
  {
    kind: 'sofa-two',
    category: 'Living',
    name: 'Two-seat sofa',
    description: 'Two cushions & padded arms',
    width: 60,
    depth: 34,
    height: 34,
    elevation: 0,
    color: '#a3a18b',
  },
  {
    kind: 'sofa-corner',
    category: 'Living',
    name: 'Corner sofa',
    description: 'L-shaped with left or right return',
    width: 96,
    depth: 66,
    height: 34,
    elevation: 0,
    color: '#899d99',
  },
  {
    kind: 'tea-table',
    category: 'Living',
    name: 'Tea table',
    description: 'Low table for the sofa set',
    width: 36,
    depth: 20,
    height: 18,
    elevation: 0,
    color: '#b99570',
  },
  {
    kind: 'cabinet',
    category: 'Storage',
    name: 'Wall cabinet',
    description: 'Adjustable mounting height',
    width: 36,
    depth: 14,
    height: 30,
    elevation: 54,
    color: '#c0a583',
  },
  {
    kind: 'fridge',
    category: 'Kitchen & laundry',
    name: 'Refrigerator',
    description: 'Full-height appliance',
    width: 30,
    depth: 28,
    height: 68,
    elevation: 0,
    color: '#b8c4c2',
  },
  {
    kind: 'washer',
    category: 'Kitchen & laundry',
    name: 'Washing machine',
    description: 'Front-loading appliance',
    width: 27,
    depth: 27,
    height: 38,
    elevation: 0,
    color: '#e6e7e3',
  },
  {
    kind: 'desk',
    category: 'Dining & work',
    name: 'Reading table',
    description: 'Your everyday workspace',
    width: 42,
    depth: 24,
    height: 30,
    elevation: 0,
    color: '#c5a17e',
  },
  {
    kind: 'dining',
    category: 'Dining & work',
    name: 'Dining table',
    description: 'Table footprint, without chairs',
    width: 60,
    depth: 36,
    height: 30,
    elevation: 0,
    color: '#b18b69',
  },
  {
    kind: 'chair',
    category: 'Dining & work',
    name: 'Chair',
    description: 'Wooden seat & slatted back',
    width: 41 / 2.54,
    depth: 45 / 2.54,
    height: 100 / 2.54,
    elevation: 0,
    color: '#b48858',
  },
  {
    kind: 'custom',
    category: 'Make it yours',
    name: 'Custom object',
    description: 'Anything, in any size',
    width: 24,
    depth: 24,
    height: 24,
    elevation: 0,
    color: '#c2937c',
  },
  {
    kind: 'nightstand',
    category: 'Bedroom',
    name: 'Nightstand',
    description: 'Bedside table with two drawers',
    width: 22,
    depth: 18,
    height: 24,
    elevation: 0,
    color: '#b99570',
  },
  {
    kind: 'dresser',
    category: 'Bedroom',
    name: 'Chest of drawers',
    description: 'Wide bedroom dresser with six drawers',
    width: 54,
    depth: 20,
    height: 34,
    elevation: 0,
    color: '#b28c69',
  },
  {
    kind: 'crib',
    category: 'Bedroom',
    name: 'Baby crib',
    description: 'Nursery cot with mattress and slatted rails',
    width: 30,
    depth: 56,
    height: 38,
    elevation: 0,
    color: '#d9cbb6',
  },
  {
    kind: 'bunk-bed',
    category: 'Bedroom',
    name: 'Bunk bed',
    description: 'Two single mattresses, guard rails and ladder',
    width: 42,
    depth: 80,
    height: 68,
    elevation: 0,
    color: '#a48262',
  },
  {
    kind: 'ottoman',
    category: 'Living',
    name: 'Ottoman',
    description: 'Padded footstool or extra seat',
    width: 28,
    depth: 22,
    height: 17,
    elevation: 0,
    color: '#bd9b87',
  },
  {
    kind: 'bench',
    category: 'Living',
    name: 'Upholstered bench',
    description: 'Long padded seat with wooden legs',
    width: 48,
    depth: 18,
    height: 19,
    elevation: 0,
    color: '#899d99',
  },
  {
    kind: 'console-table',
    category: 'Living',
    name: 'Console table',
    description: 'Narrow hallway table with lower shelf',
    width: 48,
    depth: 14,
    height: 32,
    elevation: 0,
    color: '#b99570',
  },
  {
    kind: 'tv-unit',
    category: 'Living',
    name: 'TV stand',
    description: 'Low media console with open center shelves',
    width: 60,
    depth: 18,
    height: 22,
    elevation: 0,
    color: '#a48262',
  },
  {
    kind: 'bookcase',
    category: 'Storage',
    name: 'Bookcase',
    description: 'Tall open bookshelf with five shelves',
    width: 32,
    depth: 12,
    height: 72,
    elevation: 0,
    color: '#c0a583',
  },
  {
    kind: 'shoe-rack',
    category: 'Storage',
    name: 'Shoe rack',
    description: 'Low entryway storage with three shelves',
    width: 32,
    depth: 12,
    height: 24,
    elevation: 0,
    color: '#a48262',
  },
  {
    kind: 'side-table',
    category: 'Living',
    name: 'Side table',
    description: 'Compact end table beside a sofa or armchair',
    width: 20,
    depth: 20,
    height: 22,
    elevation: 0,
    color: '#c5a17e',
  },
  {
    kind: 'office-chair',
    category: 'Dining & work',
    name: 'Office chair',
    description: 'Desk chair with padded back, arms and wheel base',
    width: 26,
    depth: 26,
    height: 42,
    elevation: 0,
    color: '#58696b',
  },
  {
    kind: 'bar-stool',
    category: 'Dining & work',
    name: 'Bar stool',
    description: 'High kitchen counter seat with footrest',
    width: 18,
    depth: 18,
    height: 30,
    elevation: 0,
    color: '#b48858',
  },
  {
    kind: 'work-desk',
    category: 'Dining & work',
    name: 'Office desk',
    description: 'Wide desk with a drawer pedestal',
    width: 60,
    depth: 28,
    height: 30,
    elevation: 0,
    color: '#c5a17e',
  },
  {
    kind: 'kitchen-base',
    category: 'Kitchen & laundry',
    name: 'Base cabinet',
    description: 'Kitchen counter with two doors and worktop',
    width: 36,
    depth: 24,
    height: 36,
    elevation: 0,
    color: '#b2bdaa',
  },
  {
    kind: 'kitchen-sink',
    category: 'Kitchen & laundry',
    name: 'Kitchen sink',
    description: 'Sink cabinet with inset basin, tap and draining board',
    width: 36,
    depth: 24,
    height: 42,
    elevation: 0,
    color: '#b2bdaa',
  },
  {
    kind: 'kitchen-island',
    category: 'Kitchen & laundry',
    name: 'Kitchen island',
    description: 'Freestanding preparation counter with storage',
    width: 60,
    depth: 36,
    height: 36,
    elevation: 0,
    color: '#a5b3a4',
  },
  {
    kind: 'stove',
    category: 'Kitchen & laundry',
    name: 'Stove & oven',
    description: 'Freestanding cooker with four burners and oven',
    width: 30,
    depth: 26,
    height: 36,
    elevation: 0,
    color: '#d0d5d3',
  },
  {
    kind: 'dishwasher',
    category: 'Kitchen & laundry',
    name: 'Dishwasher',
    description: 'Under-counter appliance with front controls',
    width: 24,
    depth: 24,
    height: 34,
    elevation: 0,
    color: '#c4cecb',
  },
  {
    kind: 'microwave',
    category: 'Kitchen & laundry',
    name: 'Microwave',
    description: 'Countertop oven; starts 36 inches above the floor',
    width: 22,
    depth: 17,
    height: 13,
    elevation: 36,
    color: '#c4cecb',
  },
  {
    kind: 'pantry',
    category: 'Storage',
    name: 'Pantry cupboard',
    description: 'Tall kitchen cabinet with four doors',
    width: 30,
    depth: 24,
    height: 84,
    elevation: 0,
    color: '#b2bdaa',
  },
  {
    kind: 'toilet',
    category: 'Bathroom',
    name: 'Toilet',
    description: 'Toilet bowl, seat and cistern',
    width: 18,
    depth: 28,
    height: 30,
    elevation: 0,
    color: '#eceee8',
  },
  {
    kind: 'squat-toilet',
    category: 'Bathroom',
    name: 'Squat toilet pan',
    description: 'Floor-level pan toilet with two footrests and a recessed bowl',
    width: 24,
    depth: 28,
    height: 3,
    elevation: 0,
    color: '#eceee8',
  },
  {
    kind: 'bathroom-vanity',
    category: 'Bathroom',
    name: 'Bathroom vanity',
    description: 'Wash basin, tap and two-door cabinet',
    width: 30,
    depth: 22,
    height: 40,
    elevation: 0,
    color: '#a3b7b5',
  },
  {
    kind: 'bathtub',
    category: 'Bathroom',
    name: 'Bathtub',
    description: 'Freestanding tub with inset bathing well',
    width: 32,
    depth: 60,
    height: 24,
    elevation: 0,
    color: '#e9ede7',
  },
  {
    kind: 'shower',
    category: 'Bathroom',
    name: 'Shower enclosure',
    description: 'Square shower tray, glass panels and shower head',
    width: 36,
    depth: 36,
    height: 80,
    elevation: 0,
    color: '#c5d7d6',
  },
  {
    kind: 'floor-lamp',
    category: 'Decor & utility',
    name: 'Floor lamp',
    description: 'Standing lamp with shade and round base',
    width: 16,
    depth: 16,
    height: 62,
    elevation: 0,
    color: '#ddd1b6',
  },
  {
    kind: 'table-lamp',
    category: 'Decor & utility',
    name: 'Table lamp',
    description: 'Bedside lamp; starts 24 inches above the floor',
    width: 12,
    depth: 12,
    height: 22,
    elevation: 24,
    color: '#d5b893',
  },
  {
    kind: 'plant',
    category: 'Decor & utility',
    name: 'Potted plant',
    description: 'Indoor leafy plant in a round planter',
    width: 22,
    depth: 22,
    height: 48,
    elevation: 0,
    color: '#ad8062',
  },
  {
    kind: 'rug',
    category: 'Decor & utility',
    name: 'Area rug',
    description: 'Flat floor textile; furniture can sit on top',
    width: 60,
    depth: 84,
    height: 0.5,
    elevation: 0,
    color: '#b5a590',
  },
  {
    kind: 'mirror',
    category: 'Decor & utility',
    name: 'Wall mirror',
    description: 'Framed mirror; starts 36 inches above the floor',
    width: 24,
    depth: 2,
    height: 36,
    elevation: 36,
    color: '#b99570',
  },
  {
    kind: 'coat-rack',
    category: 'Decor & utility',
    name: 'Coat rack',
    description: 'Standing hallway coat stand with hooks',
    width: 22,
    depth: 22,
    height: 68,
    elevation: 0,
    color: '#a48262',
  },
  {
    kind: 'laundry-basket',
    category: 'Decor & utility',
    name: 'Laundry basket',
    description: 'Open hamper for clothes and linen',
    width: 18,
    depth: 18,
    height: 24,
    elevation: 0,
    color: '#bdac8f',
  },
] as const satisfies readonly CatalogPreset[]

export type ItemKind = (typeof CATALOG)[number]['kind']

export function filterCatalog(query: string, category: CatalogCategory | 'All' = 'All') {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean)
  return CATALOG.filter((item) => {
    const text = `${item.category} ${item.name} ${item.description}`.toLowerCase()
    return (
      (category === 'All' || item.category === category) &&
      words.every((word) => text.includes(word))
    )
  })
}
